name: EventBuilders
version: '${project.version}'
main: fun.dalynkaa.eventbuilders.EventBuilders
api-version: 1.19
load: POSTWORLD
soft-depend:
  - ItemsAdder
commands:
  game:
    aliases:
      - sp
  user:
    permission: spbuild.admin
permissions:
  spbuild.admin:
    description: Main
